version: '3'

services:
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  smtp:
    image: rnwood/smtp4dev
    restart: always
    ports:
      - "143:143"   # IMAP
      - "1025:1025" # SMTP
      - "5000:80"   # Web interface
    volumes:
      - ./smtp4dev-data:/smtp4dev # This is where smtp4dev stores its database
    environment:
      - ServerOptions__HostName=smtp4dev
      - ServerOptions__Port=1025
      - ServerOptions__TlsMode=StartTls
