version: '2'

services:
  smtp:
    image: rnwood/smtp4dev
    restart: always
    ports:
      - "143:143"   # IMAP
      - "1025:1025" # SMTP
      - "5000:80"   # Web interface
    volumes:
      - ./smtp4dev-data:/smtp4dev # This is where smtp4dev stores its database
    environment:
      - ServerOptions__HostName=smtp4dev
      - ServerOptions__Port=1025
      - ServerOptions__TlsMode=StartTls

volumes:
  smtp4dev-data:
    external: true
