#!/usr/bin/env bash

pnpm exec grpc_tools_node_protoc \
    --js_out=import_style=commonjs,binary:./generated \
    --grpc_out=grpc_js:./generated \
    -I ../protos \
    ../protos/*.proto

pnpm exec protoc \
    --plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts \
    --ts_out=grpc_js:./generated \
    -I ../protos \
    ../protos/*.proto
